# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://Mrlove133481.github.io/
date_format: "ordinal"
title: Mrlove
subtitle: "一目倾心,再别难忘"
description: "归来仍是少年"
keywords: Mrlove
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Mrlove
organization: 
organization_url: 
github_username: Mrlove133481
location: ChengDu, China
email: 1334819077@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
     href: /archives/
     label: 归档

  -
    href: /jottings/
    label: 随笔

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    jottings:
        output: true
        permalink: /jottings/:path/

repository: Mrlove133481/Mrlove133481.github.io/
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
 #   username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
 #   owner: 
  #  repo: blog-comments
   # oauth:
    #    client_id: 
     #   client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Mrlove133481
    repo: BlogComments
    clientID: 369cd4b9551f3590c4ce
    clientSecret: a50d575335bd863643c9187397195c89cc1dedd4
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
